config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'sessions/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  get '/signupadmin', to: 'admin/admins#new'
  resources :admins
  resources :posts
  resources :account_activations, only: [:edit]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
Tutorial</em></a>, part of the
<a href="https://www.learnenough.com/">Learn Enough</a> family of
tutorials, is a
<a href="https://www.railstutorial.org/book">book</a> and
<a href="https://screencasts.railstutorial.org/">screencast series</a>
to teach web development with

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
Contact the Ruby on Rails Tutorial about the sample app at the
<a href="https://www.railstutorial.org/contact">contact page</a>.
<%= link_to "Sign up now!", signupadmin_path, class: "btn btn-lg btn-primary" %>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
Get help on the Ruby on Rails Tutorial at the
<a href="http://www.railstutorial.org/help">Rails
Tutorial help
page</a>.
To get help on this sample app, see the
<a href="http://www.railstutorial.org/book"><em>Ruby
on Rails
Tutorial</em> book</a>.
</p>

app/views/static_pages/home.html.erb
<div id="carousel" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("0.avif", class: "w-100", height: "650") %>
      <div class="carousel-caption">
          <div class="container">
              <div class="row d-flex justify-content-start text-center">
                 <div class="col-6 bg-custom d-none d-lg-block py-5 px-0 pl-5">
                    <h1>Princeless</h1>
                    <div class="border-top border-primary w-50 mx-auto my-3"></div>
                    <h3 class="pb-3">Complete Website Design</h3>
                    <%= link_to "Get Start", signup_path , class: "btn btn-first btn-lg" %>
                    <a href="#" class="btn btn-second btn-lg">View Now</a>
                 </div>
              </div>
          </div>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag("1.jpg", class: "w-100", height: "650") %>
      <div class="carousel-caption">
          <div class="container">
              <div class="row d-flex justify-content-center text-center">
                 <div class="col-6 bg-custom d-none d-lg-block py-5 px-0">
                    <h1>Princeless</h1>
                    <div class="border-top border-primary w-50 mx-auto my-3"></div>
                    <h3 class="pb-3">Complete Website Design</h3>
                    <%= link_to "Get Start", signup_path , class: "btn btn-first btn-lg" %>
                    <a href="#" class="btn btn-second btn-lg">View Now</a>
                 </div>
              </div>
          </div>
      </div>
    </div>
     <div class="carousel-item">
      <%= image_tag("1.webp", class: "w-100", height: "650") %>
      <div class="carousel-caption">
          <div class="container">
              <div class="row d-flex justify-content-end text-right">
                 <div class="col-6 bg-custom d-none d-lg-block py-5 px-0 pl-5">
                    <h1>Princeless</h1>
                    <div class="border-top border-primary w-50"></div>
                    <h3 class="pb-3">Complete Website Design</h3>
                    <%= link_to "Get Start", signup_path , class: "btn btn-first btn-lg" %>
                    <a href="#" class="btn btn-second btn-lg">View Now</a>
                 </div>
              </div>
          </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>